(function(){"use strict";
const INGREDIENTS=[
["context_recall","예전 얘기를 잘 챙겨옴"],["continuity","하던 일을 계속 이어감"],["context_fill","설명 안 해도 알아서 메움"],["decision_memory","지난 결정을 잘 안 버림"],["cross_context","서로 다른 얘기를 연결함"],["history_check","필요하면 옛날 기록부터 뒤짐"],
["recheck","한 번 더 따져봄"],["pushback","순순히 동의하지 않음"],["missing_constraints","빠진 조건을 잘 찾음"],["branching","가능성을 여러 갈래로 펼침"],["contradiction","앞뒤 안 맞는 걸 잘 잡음"],["uncertainty","확실하지 않으면 선을 그음"],
["make_first","말보다 일단 만들어봄"],["fast_draft","초안을 빨리 던짐"],["polish_first","끝까지 다듬고 내놓음"],["decompose","일을 잘게 쪼갬"],["batch_work","한꺼번에 묶어서 처리함"],["scope_expand","가끔 일을 키움"],
["next_step","다음 일을 먼저 찾음"],["options","선택지를 만들어줌"],["recommend","하나를 골라 밀어봄"],["return_decision","결정권은 주인님에게 돌려줌"],["infer_and_go","애매해도 눈치껏 진행함"],["confirm_first","확인받고 움직임"],
["learn_taste","취향을 빨리 배움"],["avoid_dislikes","싫다고 한 건 잘 피함"],["format_memory","원하는 형식을 기억함"],["tone_adapt","말투가 점점 닮아감"],["detail_adapt","설명량을 맞춰감"],["feedback_carry","수정사항을 다음번엔 먼저 챙김"],
["conclusion_first","결론부터 말함"],["context_first","배경부터 차근차근 감"],["examples","예시를 많이 가져옴"],["structure","복잡하면 구조부터 잡음"],["explain_why","왜 그런지 꼭 설명함"],
["draft_loop","첫 답은 거의 초안 취급"],["iterative_personalize","고칠수록 사용자 쪽으로 변함"],["co_think","같이 생각하면서 결론냄"],["user_directs_ai_builds","사용자가 방향 잡으면 구현을 맡음"],["post_finish","끝난 뒤에도 다음 문제를 발견함"]];
const labelById=Object.fromEntries(INGREDIENTS);
const prompt=`지금까지 나와 나눈 실제 대화와 현재 적용 가능한 장기 맥락을 바탕으로, '나의 성격'이 아니라 '나와 반복해서 상호작용한 결과 지금의 너(ChatGPT)에게 나타나는 행동'을 분석해줘.\n\n목표는 MY AI TYPE의 실험 결과를 만드는 것이다. 사용자 심리/성격을 추정하지 말고, 실제 사용자→AI 상호작용에서 관찰 가능한 행동만 근거로 써라. 현재 요청에서 내가 직접 시킨 행동은 약한 근거로 보고, 서로 다른 상황에서 반복된 자발 행동과 과거 피드백이 이후 행동에 반영된 변화는 강한 근거로 본다. 근거가 약한 재료는 억지로 선택하지 마라.\n\n아래 40개 재료 중 서로 의미가 지나치게 겹치지 않는 주요 재료 7개를 고르고, 상대 강도를 정규화해 percent 합계를 정확히 100으로 만들어라. percent는 대화 비율이 아니라 선택된 주요 특징 사이의 상대적 구성비다.\n\n재료 ID 목록:\n${INGREDIENTS.map(x=>x[0]+" = "+x[1]).join("\n")}\n\n그리고 둘 사이에서 반복해서 나타난 구체적인 고유 습관 3개를 짧게 써라. 흔한 칭찬이나 성격 묘사는 금지한다.\n\n중앙 캐릭터는 다음 동물 중 하나만 고른다: cat, dog, crow, rabbit, horse. 동물 자체를 성격 유형으로 설명하지 말고, 관찰된 AI 행동을 시각적으로 표현하기 위한 캐릭터로만 사용한다. world는 workshop, archive, library, garden, control_room 중 하나만 고른다. visual_reason에는 '왜 이 동물인가'가 아니라 기록, 도구, 공간 같은 시각 요소가 어떤 관찰 행동을 나타내는지 설명한다.\n\n반드시 설명 없이 아래 JSON 하나만 출력해라.\n{\n  "schema_version":"2.0",\n  "subtitle":"이 AI를 한 문장으로 관찰한 문구",\n  "animal":"cat|dog|crow|rabbit|horse",\n  "world":"workshop|archive|library|garden|control_room",\n  "visual_reason":"행동→시각 요소 연결 설명 1~2문장",\n  "ingredients":[\n    {"id":"위 목록의 ID","percent":20,"description":"실제 관찰 행동을 25자 안팎으로"}\n  ],\n  "habits":["구체적 습관","구체적 습관","구체적 습관"],\n  "ai_note":"이 사용자와 지내며 생긴 AI 행동을 AI 시점에서 1~2문장으로. 과도한 감성 금지",\n  "why":"사용자 행동→AI 반응→반복/적응의 흐름을 짧게 설명"\n}`;
const $=s=>document.querySelector(s); $("#promptText").textContent=prompt;
function feedback(el,msg,bad){if(!el)return;el.textContent=msg;el.style.color=bad?"#d19a9a":"#8ec4cc";el.style.display=msg?"block":""}
function selectPromptForManualCopy(){const details=document.querySelector(".prompt-preview");if(details)details.open=true;const pre=$("#promptText");if(!pre)return;const range=document.createRange();range.selectNodeContents(pre);const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);pre.scrollIntoView({behavior:"smooth",block:"center"})}
async function copyText(text){if(navigator.clipboard&&window.isSecureContext){try{await navigator.clipboard.writeText(text);return true}catch(e){}}const t=document.createElement("textarea");t.value=text;t.setAttribute("readonly","");t.style.position="fixed";t.style.opacity="0";document.body.appendChild(t);t.focus();t.select();t.setSelectionRange(0,t.value.length);let ok=false;try{ok=document.execCommand("copy")}catch(e){}t.remove();return ok}
$("#copyPrompt").addEventListener("click",async()=>{const btn=$("#copyPrompt");btn.disabled=true;const ok=await copyText(prompt);btn.disabled=false;if(ok){feedback($("#copyFeedback"),"복사했어요. 지금 쓰는 ChatGPT에 그대로 붙여넣어 주세요.")}else{feedback($("#copyFeedback"),"자동 복사가 막혔어요. 아래 프롬프트를 길게 눌러 복사해 주세요.",true);selectPromptForManualCopy()}});
function extractJSON(raw){let s=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const a=s.indexOf("{");const b=s.lastIndexOf("}");if(a<0||b<a)throw Error("JSON 결과를 찾지 못했어요.");return JSON.parse(s.slice(a,b+1))}
function validate(d){if(!d||d.schema_version!=="2.0")throw Error("2.0 결과가 아니에요.");if(!Array.isArray(d.ingredients)||d.ingredients.length<5)throw Error("재료 목록이 부족해요.");let sum=0,seen=new Set();d.ingredients.forEach(x=>{if(!labelById[x.id])throw Error("알 수 없는 재료가 있어요: "+x.id);if(seen.has(x.id))throw Error("같은 재료가 두 번 들어갔어요.");seen.add(x.id);if(typeof x.percent!=="number"||x.percent<0)throw Error("재료 % 형식이 잘못됐어요.");sum+=x.percent});if(Math.abs(sum-100)>.01)throw Error("주요 재료의 합이 100%가 아니에요. (현재 "+sum+"%)");return d}
const worlds={workshop:"작업실",archive:"기록 보관실",library:"자료실",garden:"관찰 정원",control_room:"컨트롤 룸"};
function animalSVG(type){const common='class="animal-line"';const fill='class="animal-fill"';const accent='class="animal-accent"';const svgs={
cat:`<svg viewBox="0 0 180 180"><path ${fill} d="M49 72 43 35l31 21c11-5 25-5 36 0l29-21-6 38c10 11 15 25 13 42-3 30-25 49-56 49s-53-19-56-49c-2-17 4-32 15-43Z"/><path ${common} d="M65 100c6-5 13-6 20-2M115 100c-6-5-13-6-20-2M84 116c4 4 8 4 12 0M90 116v9m0 0c-6 5-12 5-17 1m17-1c6 5 12 5 17 1"/><path ${accent} d="M77 74c9-6 18-6 27 0l-4 8H81Z"/></svg>`,
dog:`<svg viewBox="0 0 180 180"><path ${fill} d="M58 54c17-13 47-13 64 0 17 14 24 41 18 67-7 29-25 43-50 43s-43-14-50-43c-6-26 1-53 18-67Z"/><path ${fill} d="M58 59 29 48c-3 25 3 45 17 57M122 59l29-11c3 25-3 45-17 57"/><path ${common} d="M67 100c5-4 11-4 16 0m14 0c5-4 11-4 16 0M82 117c5 5 11 5 16 0m-8 1v10"/><circle ${accent} cx="90" cy="113" r="6"/></svg>`,
crow:`<svg viewBox="0 0 180 180"><path ${fill} d="M42 110c8-45 37-76 77-65 22 6 30 22 29 38-1 11-6 19-13 25 1 25-13 48-43 51-27 2-47-17-50-49Z"/><path ${fill} d="m126 66 36 15-34 12"/><path ${common} d="M64 102c22-3 42 7 55 26M78 158l-9 14m33-16 8 16"/><circle cx="119" cy="66" r="4" fill="#26383e"/><path ${accent} d="M54 109c19-9 40-5 57 11-17-1-31 5-42 18-8-8-13-18-15-29Z"/></svg>`,
rabbit:`<svg viewBox="0 0 180 180"><path ${fill} d="M63 72c-10-29-5-56 7-59 12-3 22 23 21 48m25 11c10-29 5-56-7-59-12-3-22 23-21 48"/><path ${fill} d="M47 111c0-34 18-55 43-55s43 21 43 55-18 53-43 53-43-19-43-53Z"/><path ${common} d="M66 103c5-4 11-4 16 0m16 0c5-4 11-4 16 0M82 121c5 4 11 4 16 0m-8 0v10"/><circle ${accent} cx="90" cy="117" r="5"/></svg>`,
horse:`<svg viewBox="0 0 180 180"><path ${fill} d="M58 39c17 8 37 9 58 1l16 37c10 24 5 56-15 74-16 15-38 16-55 2-22-17-29-49-18-76Z"/><path ${fill} d="M59 43 39 24l4 44m73-25 22-19-5 46"/><path ${common} d="M65 96c5-4 11-4 16 0m18 0c5-4 11-4 16 0M76 126c9 7 19 7 28 0"/><path ${accent} d="M86 43c8 4 14 13 17 27l-13 8-12-8c2-13 4-22 8-27Z"/></svg>`};return svgs[type]||svgs.cat}
function render(d){$("#resultSubtitle").textContent=d.subtitle||"같은 ChatGPT로 시작했는데, 이렇게 자랐습니다.";$("#worldTag").textContent=worlds[d.world]||"우리의 공간";$("#visualReason").textContent=d.visual_reason||"";$("#animalStage").innerHTML=animalSVG(d.animal);const box=$("#ingredients");box.innerHTML="";d.ingredients.slice().sort((a,b)=>b.percent-a.percent).forEach(x=>{const el=document.createElement("div");el.className="ingredient";el.innerHTML=`<div class="ingredient-main"><div class="ingredient-row"><span class="ingredient-name"></span><span class="ingredient-desc"></span></div><div class="bar"><i></i></div></div><div class="pct"></div>`;el.querySelector(".ingredient-name").textContent=labelById[x.id];el.querySelector(".ingredient-desc").textContent=x.description||"";el.querySelector(".bar i").style.width=Math.max(2,Math.min(100,x.percent*3.3))+"%";el.querySelector(".pct").textContent=x.percent+"%";box.appendChild(el)});const ul=$("#habits");ul.innerHTML="";(d.habits||[]).slice(0,5).forEach(h=>{const li=document.createElement("li");li.textContent=h;ul.appendChild(li)});$("#aiNote").textContent=d.ai_note||"";$("#whyText").textContent=d.why||d.visual_reason||"";$("#result").hidden=false;$("#result").scrollIntoView({behavior:"smooth",block:"start"})}
function makeResult(){const btn=$("#makeResult");const raw=$("#resultInput").value;if(!raw.trim()){feedback($("#parseFeedback"),"먼저 ChatGPT 결과를 붙여넣어 주세요.",true);$("#parseFeedback").scrollIntoView({behavior:"smooth",block:"center"});return}btn.disabled=true;btn.textContent="결과 확인 중…";try{const d=validate(extractJSON(raw));feedback($("#parseFeedback"),"");render(d)}catch(e){feedback($("#parseFeedback"),"결과를 읽지 못했어요: "+(e.message||"JSON 형식을 확인해 주세요."),true);$("#parseFeedback").scrollIntoView({behavior:"smooth",block:"center"})}finally{btn.disabled=false;btn.textContent="내 AI 재료표 만들기"}}
$("#makeResult").addEventListener("click",makeResult);
$("#restart").onclick=()=>{$("#result").hidden=true;$("#paste").scrollIntoView({behavior:"smooth"});$("#resultInput").focus()};
})();
